"""UI module package for T-TEA generated PySide6 classes.

This package provides UI classes generated by pyside6-uic, including
forms and dialogs used across the application.

Attributes
----------
__version__ : str
    Current package version.
__date__ : str
    Release date of the package version.
__author__ : str
    Package author or team.
__license__ : str
    Package license.

See Also
--------
PlayerListView
    Lists player data in a structured format.

Notes
-----
This package is maintained by the Larva UDESC team and is under active
development.

Contributions and bug reports are welcome at:
https://github.com/larvattea/ttea
"""

# Define the __all__ variable
__all__ = [
    "Ui_AboutView",
    "Ui_AutomaticCalibrationView",
    "Ui_CalibrationSettingView",
    "Ui_CalibrationView",
    "Ui_InstitutionFacilityEditView",
    "Ui_InstitutionFacilityListView",
    "Ui_LanguageView",
    "Ui_MainView",
    "Ui_ManualCalibrationView",
    "Ui_PlayerEditView",
    "Ui_PlayerGameLaunchView",
    "Ui_PlayerListView",
    "Ui_ProfessionalEditView",
    "Ui_ProfessionalListView",
]

__version__ = "1.0.0"
__date__ = "2025-12-25"
__author__ = "Larva UDESC"
__license__ = "MIT License"

# Import the submodules
from .aboutviewui import Ui_AboutView
from .automaticcalibrationviewui import Ui_AutomaticCalibrationView
from .calibrationsettingviewui import Ui_CalibrationSettingView
from .calibrationviewui import Ui_CalibrationView
from .institutionfacilityeditviewui import Ui_InstitutionFacilityEditView
from .institutionfacilitylistviewui import Ui_InstitutionFacilityListView
from .languageviewui import Ui_LanguageView
from .mainviewui import Ui_MainView
from .manualcalibrationviewui import Ui_ManualCalibrationView
from .playereditviewui import Ui_PlayerEditView
from .playergamelaunchviewui import Ui_PlayerGameLaunchView
from .playerlistviewui import Ui_PlayerListView
from .professionaleditviewui import Ui_ProfessionalEditView
from .professionallistviewui import Ui_ProfessionalListView
